import React from 'react';

export const SECTIONS = {
  harassment: {
    key: 'harassment' as const,
    slug: '/harassment',
    nameBn: 'হয়রানি ও নির্যাতনের বিরুদ্ধে জানান',
    nameEn: 'Report Harassment & Abuse',
    shortNameBn: 'হয়রানি',
    shortNameEn: 'Harassment',
    descriptionBn: 'শারীরিক বা মানসিক নির্যাতন, প্রতারণা ও অনলাইনে হেনস্তার অভিযোগ দায়িত্বশীলভাবে প্রকাশ করুন।',
    descriptionEn: 'Report physical or psychological abuse, relationship deception, or online harassment responsibly.',
    primaryColor: '#B84A62',
    hoverColor: '#9E384E',
    bgColor: '#FDF2F4',
    borderColor: '#F7CCD5',
    textColor: '#8B293E',
    colors: {
      primary: '#B84A62',
      hover: '#9E384E',
      lightBg: '#FDF2F4',
      bgLight: '#FDF2F4',
      border: '#F7CCD5',
      text: '#8B293E',
      textSafe: '#8B293E',
      filledText: '#FFFFFF',
    },
  },
  rickshaw: {
    key: 'rickshaw' as const,
    slug: '/rickshaw',
    nameBn: 'অবৈধ চার্জিং স্টেশন প্রকাশ করুন',
    nameEn: 'Expose Unsafe Charging Stations',
    shortNameBn: 'চার্জিং',
    shortNameEn: 'Charging',
    descriptionBn: 'আবাসিক বা ঝুঁকিপূর্ণ এলাকায় অননুমোদিত চার্জিং স্টেশন ও অনিরাপদ সংযোগের তথ্য জানান।',
    descriptionEn: 'Report locations and hazards of unauthorized auto-rickshaw battery charging stations.',
    primaryColor: '#D9822B',
    hoverColor: '#B8681A',
    bgColor: '#FEF7EE',
    borderColor: '#FBDDB9',
    textColor: '#9A530C',
    colors: {
      primary: '#D9822B',
      hover: '#B8681A',
      lightBg: '#FEF7EE',
      bgLight: '#FEF7EE',
      border: '#FBDDB9',
      text: '#9A530C',
      textSafe: '#9A530C',
      filledText: '#050505',
    },
  },
  extortion: {
    key: 'extortion' as const,
    slug: '/extortion',
    nameBn: 'চাঁদাবাজির তথ্য প্রকাশ করুন',
    nameEn: 'Report Local Extortion',
    shortNameBn: 'চাঁদাবাজি',
    shortNameEn: 'Extortion',
    descriptionBn: 'দোকানপাট, বাজার, পরিবহন স্ট্যান্ড বা নির্মাণকাজে জোরপূর্বক অর্থ আদায় ও হুমকির বিরুদ্ধে তথ্য দিন।',
    descriptionEn: 'Report forced collections, extortion, and coercive illegal demands in local areas.',
    primaryColor: '#4F5D95',
    hoverColor: '#3E4A7A',
    bgColor: '#F0F3F9',
    borderColor: '#CCD5E8',
    textColor: '#333E67',
    colors: {
      primary: '#4F5D95',
      hover: '#3E4A7A',
      lightBg: '#F0F3F9',
      bgLight: '#F0F3F9',
      border: '#CCD5E8',
      text: '#333E67',
      textSafe: '#333E67',
      filledText: '#FFFFFF',
    },
  },
};

export type SectionKey = keyof typeof SECTIONS;

export const THEME_PALETTE = {
  light: {
    page: '#F0F2F5',
    surface: '#FFFFFF',
    surfaceSubtle: '#F0F2F5',
    surfaceElevated: '#FFFFFF',
    surfaceHover: '#E4E6EB',
    textPrimary: '#050505',
    textSecondary: '#65676B',
    textMuted: '#65676B',
    textInverse: '#FFFFFF',
    borderSubtle: '#E4E6EB',
    border: '#E4E6EB',
    borderStrong: '#E4E6EB',
    accent: '#3A7CA5',
    primary: '#1B4D6B',
    primaryHover: '#163B52',
    primaryActive: '#245F82',
  },
  dark: {
    page: '#18191A',
    surface: '#242526',
    surfaceSubtle: '#242526',
    surfaceElevated: '#242526',
    surfaceHover: '#3A3B3C',
    textPrimary: '#E4E6EB',
    textSecondary: '#B0B3B8',
    textMuted: '#B0B3B8',
    textInverse: '#FFFFFF',
    borderSubtle: '#3A3B3C',
    border: '#3A3B3C',
    borderStrong: '#3A3B3C',
    accent: '#3A7CA5',
    primary: '#1B4D6B',
    primaryHover: '#163B52',
    primaryActive: '#245F82',
  },
  status: {
    submitted: {
      labelBn: 'জমা দেওয়া হয়েছে',
      labelEn: 'Submitted',
      color: '#65676B',
      bg: '#E4E6EB',
      darkColor: '#B0B3B8',
      darkBg: '#3A3B3C',
    },
    in_review: {
      labelBn: 'পর্যালোচনাধীন',
      labelEn: 'Under Review',
      color: '#D97706',
      bg: '#FEF3C7',
      darkColor: '#FCD34D',
      darkBg: '#2A2110',
    },
    clarification_requested: {
      labelBn: 'অতিরিক্ত তথ্য প্রয়োজন',
      labelEn: 'Clarification Needed',
      color: '#B45309',
      bg: '#FFFBEB',
      darkColor: '#FBBF24',
      darkBg: '#2E220D',
    },
    approved: {
      labelBn: 'অনুমোদিত ও প্রকাশিত',
      labelEn: 'Approved & Published',
      color: '#15803D',
      bg: '#DCFCE7',
      darkColor: '#86EFAC',
      darkBg: '#10261A',
    },
    rejected: {
      labelBn: 'বাতিলকৃত',
      labelEn: 'Rejected',
      color: '#B91C1C',
      bg: '#FEE2E2',
      darkColor: '#FCA5A5',
      darkBg: '#2B1416',
    },
  },
  feedback: {
    success: {
      text: '#15803D',
      bg: '#F0FDF4',
      border: '#BBF7D0',
      darkText: '#86EFAC',
      darkBg: '#10261A',
      darkBorder: '#1F5A35',
    },
    warning: {
      text: '#B45309',
      bg: '#FFFBEB',
      border: '#FDE68A',
      darkText: '#FCD34D',
      darkBg: '#2A2110',
      darkBorder: '#6B4E12',
    },
    error: {
      text: '#B91C1C',
      bg: '#FEF2F2',
      border: '#FECACA',
      darkText: '#FCA5A5',
      darkBg: '#2B1416',
      darkBorder: '#6B252A',
    },
    info: {
      text: '#1D4ED8',
      bg: '#EFF6FF',
      border: '#BFDBFE',
      darkText: '#93C5FD',
      darkBg: '#101E32',
      darkBorder: '#254B78',
    },
  },
};

export const LAYOUT_TOKENS = {
  navWidth: {
    desktop: '240px',
    largeDesktop: '250px',
    xlDesktop: '260px',
  },
  navLeft: {
    desktop: '16px',
    largeDesktop: '20px',
    xlDesktop: '24px',
  },
  maxWidth: {
    desktopWorkspace: 'max-w-[900px]',
    desktop1440: 'max-w-[880px]',
    desktop1536: 'max-w-[900px]',
    desktop1920: 'max-w-[920px]',
    readingColumn: 'max-w-[720px]',
    formColumn: 'max-w-[720px]',
    modal: 'max-w-xl',
  },
  gutters: {
    mobile: 'px-4',
    tablet: 'px-6',
    compactDesktop: 'px-8',
    desktop: 'px-0',
  },
  spacing: {
    pagePaddingY: {
      mobile: 'py-4',
      tablet: 'py-5',
      desktop: 'py-6',
    },
    sectionGap: {
      mobile: 'space-y-5',
      tablet: 'space-y-6',
      desktop: 'space-y-7',
    },
    cardPadding: {
      mobile: 'p-4',
      tablet: 'p-5',
      desktop: 'p-6',
    },
  },
  touchTargetMin: '44px',
};
