-- Public security hardening: keep only one equivalent published-evidence read
-- policy/helper and require the UUID identifiers generated by the Public app for
-- visitor analytics. These are storage/abuse guardrails only; no UX changes.

DROP POLICY IF EXISTS "published evidence public read" ON storage.objects;

REVOKE EXECUTE ON FUNCTION public.is_public_published_evidence(text)
  FROM anon, authenticated;

ALTER TABLE public.public_visit_sessions
  ADD CONSTRAINT public_visit_sessions_visitor_uuid_check
    CHECK (visitor_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
  ADD CONSTRAINT public_visit_sessions_session_uuid_check
    CHECK (session_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$');
