-- Privacy-minimize precise reporter device telemetry while preserving anti-abuse limits.
alter table public.complaint_submission_contexts alter column reporter_latitude drop not null,alter column reporter_longitude drop not null,alter column accuracy_meters drop not null;
create or replace function private.scrub_reporter_context_after_moderation() returns trigger language plpgsql security definer set search_path='pg_catalog','public' as $$ begin if old.status is distinct from new.status and new.status<>'submitted' then update public.complaint_submission_contexts set reporter_latitude=null,reporter_longitude=null,accuracy_meters=null,browser_name=null,browser_version=null,os_name=null,device_category=null,platform=null,language=null,timezone=null,screen_width=null,screen_height=null,user_agent=null,ui_language=null where complaint_id=new.id; end if; return new; end; $$;
revoke execute on function private.scrub_reporter_context_after_moderation() from public,anon,authenticated,service_role;
drop trigger if exists trg_scrub_reporter_context_after_moderation on public.complaints;
create trigger trg_scrub_reporter_context_after_moderation after update of status on public.complaints for each row execute function private.scrub_reporter_context_after_moderation();
create or replace function private.prune_reporter_submission_contexts() returns integer language plpgsql security definer set search_path='pg_catalog','public' as $$ declare v_deleted integer:=0; begin delete from public.complaint_submission_contexts sc using public.complaints c where c.id=sc.complaint_id and ((c.status<>'submitted' and sc.created_at<now()-interval '24 hours') or (c.status='submitted' and sc.created_at<now()-interval '7 days')); get diagnostics v_deleted=row_count; return v_deleted; end; $$;
revoke execute on function private.prune_reporter_submission_contexts() from public,anon,authenticated,service_role;
update public.complaint_submission_contexts sc set reporter_latitude=null,reporter_longitude=null,accuracy_meters=null,browser_name=null,browser_version=null,os_name=null,device_category=null,platform=null,language=null,timezone=null,screen_width=null,screen_height=null,user_agent=null,ui_language=null from public.complaints c where c.id=sc.complaint_id and c.status<>'submitted';
select private.prune_reporter_submission_contexts();
do $$ declare v_job_id bigint; begin select jobid into v_job_id from cron.job where jobname='prune-reporter-submission-contexts' limit 1;if v_job_id is not null then perform cron.unschedule(v_job_id);end if;perform cron.schedule('prune-reporter-submission-contexts','17 * * * *','select private.prune_reporter_submission_contexts();');end $$;
